### PR TITLE
Add support for Next.js >= 13.2

### LINKED ISSUE #4: run next dev found some error
hi sam3d, 

nice job! the way use websocket is very clean and easy. today i tried this plugin , but found a error in the output log. 

`this.ensureApiPage` is not a function!

can you give a full example ?  thank u

env

```
{
  "name": "ws-demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "13.2.4",
    "next-plugin-websocket": "^0.1.2",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  }
}
```

node = 16.13.2

> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
ready - loaded websocket plugin successfully
event - compiled client and server successfully in 612 ms (168 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 146 ms (169 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling / (client and server)...
event - compiled client and server successfully in 206 ms (213 modules)
error - unhandledRejection: TypeError: this.ensureApiPage is not a function

```

### PR DESCRIPTION
**Pull request by yoieh**
Fixes #4 

`ensureApiPage` was removed in `v13.1.7-canary.14`

https://github.com/vercel/next.js/pull/45716/files#diff-2f6fd5a9538abfaf3d5b76a82a8d1ffa029f84a36f0cdae5460520c5cfc2db6bL1402

### CODE REVIEW

**Review by brhx — CHANGES_REQUESTED** [review]
Excellent spot, thank you! Please could you also update the README.md with the tested version?

**Comment by yoieh** [comment]
I have updated the `Compatibility` section of the readme.
This still doesn't give full support for the new app directory with the new [Route Handlers](https://beta.nextjs.org/docs/routing/route-handlers).

**Comment by brhx** [comment]
The typescript type check fails because it needs to be aware of both possible versions of `NextNodeServer`. I'd like to ensure it doesn't

**Comment by yoieh** [comment]
I see,
There are more issues here. 

`ensurePage` only exists on the `DevServer` in version 13.3.0 and not at all `NextNodeServer`.
This PR will never work in production.

But looks like `ensureEdgeFunction` exists in both `13.1.6` and `13.3.0` and works in both dev and prod.

**Comment by yoieh** [comment]
I still kept the `ensureApiPage` for now.. 
but it look like you may be able to just use the `ensureEdgeFunction` from here on.

Not sure when i was added so can not garanti it works with a version lower than 13.1.6.
But this will "make typescript not fail".

**Review by brhx — CHANGES_REQUESTED** [review]
Oooh I like this solution! Please could you change it to just `ensureEdgeFunction` and I will give it a test and merge?
