### ISSUE TITLE
Support new the app directory's Route Handlers of Next.js v13.3

### ISSUE THREAD

**Issue by yoieh** [sam3d/next-plugin-websocket#8]
Expected working example:

```TSX
import { NextApiHandler } from "next";
import { NextWebSocketHandler } from "next-plugin-websocket";

export const socket: NextWebSocketHandler = (client, req) => {
  console.log("Client connected");

  client.on("message", (msg) => {
    client.send(msg);
  });

  client.on("close", () => {
    console.log("Client disconnected");
  });
};

export async function GET(request: Request) {
  return new Response("Upgrade Required", {
    status: 426,
  });
}
```

After PR  #6 has been merged it will give an error if you try and use the above example.

``` zsh
error - unhandledRejection: PageNotFoundError: Cannot find module for page: /api/ws
    at findPagePathData (.../node_modules/next/dist/server/dev/on-demand-entry-handler.js:272:15)
    at async Object.ensurePage (.../node_modules/next/dist/server/dev/on-demand-entry-handler.js:444:38)
    at async Server.<anonymous> (.../node_modules/next-plugin-websocket/dist/index.js:88:13) {
  code: 'ENOENT'
}
```

It only works with the old pages directory.

**Comment by yoieh** [comment]
I tried get my self a deeper understanding of how this would work with the new app dir in 13.3. 

Even if you find and require the route file socket never gets exported. 

May need to find a different approach here.
